# Generated by Django 3.2 on 2021-04-08 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование опроса')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('picture', models.ImageField(blank=True, default='/teacher.png', null=True, upload_to='customer/', verbose_name='Фотография')),
                ('email', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Адрес электронной почты')),
                ('telephone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Телефон')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.PositiveIntegerField(default=0, verbose_name='Итоговая оценка')),
                ('date', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_course', to='course.course', verbose_name='Наименование курса')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.customer', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Наименование вопроса')),
                ('mark', models.PositiveIntegerField(default=0, verbose_name='Оценка')),
                ('choice_1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вариант ответа №1')),
                ('choice_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вариант ответа №2')),
                ('choice_3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вариант ответа №3')),
                ('choice_4', models.CharField(blank=True, max_length=256, null=True, verbose_name='Вариант ответа №4')),
                ('answer', models.CharField(blank=True, choices=[('Вариант ответа №1', 'choice_1'), ('Вариант ответа №2', 'choice_2'), ('Вариант ответа №3', 'choice_3'), ('Вариант ответа №4', 'choice_4')], max_length=256, null=True, verbose_name='Правильный ответ')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_course', to='course.course', verbose_name='Наименование курса')),
            ],
        ),
    ]
