# Generated by Django 3.2 on 2021-04-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20210413_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, choices=[('Вариант ответа №1', 'choice_1'), ('choice_2', 'Вариант ответа №2'), ('choice_3', 'Вариант ответа №3'), ('choice_4', 'Вариант ответа №4')], max_length=256, null=True, verbose_name='Правильный ответ'),
        ),
    ]
