# Generated by Django 3.2 on 2021-04-14 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='customers',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Прошедшие тест'),
        ),
    ]
